CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE t_e_marque_mrq (
    mrq_id integer GENERATED BY DEFAULT AS IDENTITY,
    mrq_name character varying(100) NOT NULL,
    CONSTRAINT pk_mrq PRIMARY KEY (mrq_id)
);

CREATE TABLE t_e_typeproduit_typ (
    typ_id integer GENERATED BY DEFAULT AS IDENTITY,
    typ_nom character varying(100) NOT NULL,
    CONSTRAINT pk_typ PRIMARY KEY (typ_id)
);

CREATE TABLE t_e_produit_pdt (
    pdt_id integer GENERATED BY DEFAULT AS IDENTITY,
    pdt_nom character varying(100) NOT NULL,
    pdt_description text NULL,
    pdt_nomPhoto text NULL,
    pdt_urlPhoto text NULL,
    mrq_id integer NOT NULL,
    typ_id integer NOT NULL,
    pdt_stockreel integer NOT NULL,
    pdt_stockmin integer NOT NULL,
    pdt_stockmax integer NOT NULL,
    CONSTRAINT pk_pdt PRIMARY KEY (pdt_id),
    CONSTRAINT fk_pdt_mrq FOREIGN KEY (mrq_id) REFERENCES t_e_marque_mrq (mrq_id) ON DELETE RESTRICT,
    CONSTRAINT fk_pdt_typ FOREIGN KEY (typ_id) REFERENCES t_e_typeproduit_typ (typ_id) ON DELETE RESTRICT
);

CREATE INDEX "IX_t_e_produit_pdt_mrq_id" ON t_e_produit_pdt (mrq_id);

CREATE INDEX "IX_t_e_produit_pdt_typ_id" ON t_e_produit_pdt (typ_id);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20231004142127_CreationBDProducts', '7.0.11');

COMMIT;